---
- hosts: all
  #become: True
  tasks:
  - name: Deleting previous k8s state
    shell: kubectl delete -f /home/ubuntu/Desktop/k8s-bundle-prod.yaml
  - name: Removing previous container
    shell: docker rm -f notebook
  - name: Removing previous image
    shell: docker rmi -f mrpapdiamond/micro1:latest
  - name: Initiating K8s
    shell: minikube start --ports=192.168.213.132:30000:30000 --ports=192.168.213.132:30010:30010 --ports=192.168.213.132:30020:30020 --ports=192.168.213.132:30030:30030
  - name: Apply K8s YAML file
    shell: kubectl apply -f /home/ubuntu/Desktop/k8s-bundle-prod.yaml
  - name: Running docker container
    shell: docker run -p 3000:80 -d --name notebook mrpapdiamond/micro1
